server:
  port: 8098

spring:
  application:
    name: client-person
  datasource:
    url: "jdbc:postgresql://postgres:5432/bank"
    driverClassName: "org.postgresql.Driver"
    type: "com.zaxxer.hikari.HikariDataSource"
    username: "alvaro"
    password: "secret"
    hikari:
      connection-timeout: 20000
      maximum-idle: 4
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 180000
    jpa:
      database-platform: "org.hibernate.dialect.PostgreSQLDialect"
      show-sql: false
      properties:
        hibernate:
          #generate_statistics: true
          query:
            plan_cache_max_size: 2048
            plan_parameter_metadata_max_size: 256
          order_inserts: true
          jdbc:
            batch_size: 10
          format_sql: true